### ISSUE TITLE
Lirc Multi IR Transmitter

### ISSUE THREAD

**Issue by rossiluis22** [bengtmartensson/lirc_rpi#4]
I have compiled the mod lirc_rpi to use multiple IR transmitter on my raspberry 2 ver 3.17 and it was working like a charm, then I decided to upgrade to Jessie 4.1.12-v7+ and compiled the mod Lirc_rpi again, but when I try to send the command shows {irsend SEND_ONCE aire off}
"irsend: could not connect to socket
irsend: No such file or directory", I hope someone can help me.

**Comment by bengtmartensson** [comment]
This is a Linus proper/Debian issue, not an issue with the present driver. I suggest that you file a bug report/help request on the Lirc mailing list https://lists.sourceforge.net/lists/listinfo/lirc-list, or to Debian.
