### ISSUE TITLE
Impossible to set several pins for gpio_out_pin

### ISSUE THREAD

**Issue by peter23** [bengtmartensson/lirc_rpi#6]
Raspberry Pi 3 Model B, Raspbian Jessie, Linux 4.9.24-v7+

1) Module was successfully built using simple makefile:
```
obj-m += lirc_rpi.o

all:
        make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules

clean:
        make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean
```

2) dts was successfully compiled with `dtc -I dts -O dtb -o lirc-rpi.dtbo lirc-rpi-overlay.dts`.

3) lirc-rpi.ko replaced the file in /lib/modules and lirc-rpi.dtbo replaced the file in /boot/overlays

4)
```
# dtoverlay lirc-rpi debug=1 gpio_in_pin=21 gpio_out_pin=22,24
DTOVERLAY[error]: invalid override value '22,24' - ignored
* Failed to set gpio_out_pin=22,24
```
Why?

**Comment by bengtmartensson** [comment]
This is a problem with dt configuration; not with the present project. Please use e.g. the RPi forum. (The dt stuff is a catastrophic design, IMHO.)

BTW, I _think_ that the  line  

    brcm,pins = <23 24 25 12 16 26 18>;

defines the pins that the user _may_ use, the command line is not compatible with that. Change either one.

**Comment by bengtmartensson** [comment]
Actually, the README.md confirms the "I think" above.  

Closing.
