### ISSUE TITLE
installing guide

### ISSUE THREAD

**Issue by 0raid** [bengtmartensson/lirc_rpi#7]
Hello , is it possible to explain how to patch your file in raspberry pi???

thanks!

**Comment by bengtmartensson** [comment]
Hi,

I am afraid I do not have any installation guide. BTW, it is a "driver", not a "patch". There are numerous guides on the internet on how to compile and install an RPi driver. 

Feel free to contribute an installation guide or a HOWTO :-).

**Comment by bengtmartensson** [comment]
I have no plans to do this myself, because this project is peripheral to my interests, and, I do not consider myself an expert. Closing. 

However, contributed guides are of course welcome.
