### ISSUE TITLE
not working for me

### ISSUE THREAD

**Issue by dlemper** [bengtmartensson/lirc_rpi#9]
Hi there and merry christmas!

sorry for the bad title, but I couldn't find a better one..

I tried out your code by building the raspberry pi kernel sources after copying your files into the tree.
Then I installed everything and tried out to use irrecord. The remote I want to get lirc to learn is a Studer Revox B205. irrecord doesn't recognize the two keys that I mainly need (Input 1 and Power off).

Do you have a suggestion for me or need any more information?

Thanks so far!

**Comment by bengtmartensson** [comment]
Fröhliche Weihnachten you too!

This is not really concerning the driver, so I am closing the issue. I suggest that you mail your problem to the Lirc mailing list instead.

**Comment by bengtmartensson** [comment]
Please do post the problem on the [Lirc mailing list](https://sourceforge.net/p/lirc/mailman/) (you need to subscribe there first); I _think_ I can help you there.

**Comment by dlemper** [comment]
sorry, I didn't have enough time to do that because of the typical "Weihnachtsfeiertage" ;)

Now I mailed a text under the topic "rrecord can't recognize Studer Revox B201/B205". Hope you can get it.

Thank you!
